### ISSUE TITLE
how to calibrate?

### ISSUE THREAD

**Issue by zerog2k** [herm/ZPB30A1_Firmware#2]
Thanks for awsome work.
I have flashed mine with your latest, but seems like when I set the unit to about 500mA CC load, my power supply shows it pulling about 650mA (@13.5 VDC). Voltage appears to read very close, and the current draw reported by my power supply appears to be fairly accurate as measured with another meter - so the e-load appears to be drawing about 20% higher current than the CC set-point.

Is there some calibration procedure, e.g. data stored in eeprom, or perhaps static calibration constants we would need to fix for our units?

**Comment by herm** [comment]
Currently there is not calibration in EEPROM, but only hardcoded values in config.h.
I planned to add calibration support, but haven't done it yet. You can try changing LOAD_CAL_T manually. Reducing it by 20% should get you close to your desired value. After a few iterations you should have a pretty good calibration.

**Comment by zerog2k** [comment]
Thanks for the response.
So I attempted to adjust LOAD_CAL_T down by 20% however, it did not seem to make a difference.
I studied the current spreadsheet  (i_load.ods) briefly, and looked at the code in load.c,  and I'm guessing that the current calculation transformation is from a linear fit (F_i_pwm? = m_slope * i_set + (- t_intercept) ) of observed values? But then it is truncated by 16 bits?
```
    actual_current_setpoint = current;

    uint32_t tmp = current;
    tmp = tmp * LOAD_CAL_M - LOAD_CAL_T;
    TIM1->CCR1H = tmp >> 24;
    TIM1->CCR1L = tmp >> 16;
```

So it's not so obvious why some things are being done the way they are. (Maybe some additional code comments there, and in the spread sheet, may be helpful for understanding the methods to arrive at the calculations.)

Can you give me a few pointers on what is going on here?

Also, I did a few observations of various settings:
V_input ~= 11.9 VDC, V_load ~= 5VDC
```
#define LOAD_CAL_T 7057589L // was 8821987L
#define LOAD_CAL_M 350445L
```
I_set | I_measured | TIM1->CCR1 | V_shunt
-----|-------------|--------------|---------
500 mA | 655mA | 0x0A05 | 6.1 mV
1.00 A | 1.18 A | 0x1477 | 11.1 mV
830 mA | 1.00 A | 0x10EA | 
352 mA | 500 mA | 0x06EE | 
1.50 A | 1.72 A | 0x1EF4 | 
1.30 A | 1.50 A | 0x1AC6 |

**Comment by zerog2k** [comment]
On a side note, the design of the current set mechanism is odd: I find it strange that there is no direct feedback, i.e. amplified v_shunt resistor drop back to adc inputs of mcu, and mcu has only "blind" indirect control over the feedback loop via influencing the opamp control loop driving transistor. Maybe I'm missing something studying the schematics and the unit?

**Comment by zerog2k** [comment]
Ok, so I was able to use i_load.ods spreadsheet to plugin my actual values for measured current and pwm values, and plot my own line fit, which gave me LOAD_CAL_M = 331048 and LOAD_CAL_T = 48342429, which is within about 1-2% error over my range of 0.5-2.00 A, which is fine by me!

Thanks again, marking resolved. (Would still love to see a run-time "calibrate" function.)

**Comment by stylesuxx** [comment]
@zerog2k could you by any chance describe how your process of calibration was exactly? Where do I have to measure the PWM signal? Also the `i_load.ods` spreadsheet, where can I find that?

A friend and I bought the same device - mine is spot on after flashing - his not so much, we are now trying to find out how we can get his into a good working state - any help is greatly appreciated.

**Comment by zerog2k** [comment]
after 3 years, I don't remember any of this, lol - so whatever `zerog2k` said above ;)
for the spreadsheet, look in the `hardware` folder of this repo

**Comment by stylesuxx** [comment]
@zerog2k was worth a shot - thanks for the hint with the hardware folder, not sure how I missed that...
